```Makefile
# Makefile for OpenMP Offload microXOR

CXX ?= clang++
SM_VERSION ?= 80
SRC = src
INC = include
OBJ = obj
CXXFLAGS ?= -fopenmp -fopenmp-targets=nvptx64 -Xopenmp-target -march=sm_$(SM_VERSION) -I$(INC) -std=c++17
ifneq ($(DEBUG), yes)
	CXXFLAGS += -O3
else
	CXXFLAGS += -g
endif

CPPFILES = $(SRC)/microXOR.cpp $(SRC)/main.cpp
DEPS = $(INC)/microXOR.hpp
OBJS = $(CPPFILES:$(SRC)/%.cpp=$(OBJ)/%.o)
EXE = microXOR.exe

$(EXE): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(EXE)

$(OBJ)/%.o: $(SRC)/%.cpp $(DEPS) | obj
	$(CXX) $(CXXFLAGS) -c $< -o $@

obj:
	mkdir -p $(OBJ)

clean:
	rm -f $(OBJS) $(EXE)

.PHONY: clean
```

This Makefile is adapted for compiling the code using OpenMP offloading with Clang. It assumes the source files have been renamed from `.cu` to `.cpp` and the header files from `.cuh` to `.hpp`. The `-fopenmp` and `-fopenmp-targets=nvptx64` flags are used to enable OpenMP offloading to NVIDIA GPUs, and `-Xopenmp-target -march=sm_$(SM_VERSION)` specifies the target architecture.