```makefile
#===============================================================================
# User Options
#===============================================================================

COMPILER    ?= g++
OPTIMIZE    ?= yes
DEBUG       ?= no
PROFILE     ?= no

#===============================================================================
# Program name & source code list
#===============================================================================

program = XSBench

source = \
Main.cpp \
io.cpp \
Simulation.cpp \
GridInit.cpp \
XSutils.cpp \
Materials.cpp

obj = $(source:.cpp=.o)

#===============================================================================
# Sets Flags
#===============================================================================

# Standard Flags
CFLAGS := -std=c++17 -I$(KOKKOS_ROOT)/include

# Linker Flags
LDFLAGS = -lm -lkokkos_core -L$(KOKKOS_ROOT)/lib

# Debug Flags
ifeq ($(DEBUG),yes)
  CFLAGS += -g -G
  LDFLAGS  += -g -G
endif

# Profiling Flags
ifeq ($(PROFILE),yes)
  CFLAGS += -pg
  LDFLAGS  += -pg
endif

# Optimization Flags
ifeq ($(OPTIMIZE),yes)
  CFLAGS += -O3
endif

# Kokkos configuration
ifeq ($(findstring CUDA,$(KOKKOS_DEVICES)),CUDA)
  CFLAGS += -DKokkos_ENABLE_CUDA
endif
ifeq ($(findstring OpenMP,$(KOKKOS_DEVICES)),OpenMP)
  CFLAGS += -DKokkos_ENABLE_OPENMP
endif
ifeq ($(findstring Serial,$(KOKKOS_DEVICES)),Serial)
  CFLAGS += -DKokkos_ENABLE_SERIAL
endif


#===============================================================================
# Targets to Build
#===============================================================================

$(program): $(obj) XSbench_header.hpp XSbench_shared_header.h Makefile
	$(COMPILER) $(CFLAGS) $(obj) -o $@ $(LDFLAGS)

%.o: %.cpp XSbench_header.hpp XSbench_shared_header.h Makefile
	$(COMPILER) $(CFLAGS) -c $< -o $@

clean:
	rm -rf $(program) $(obj)

edit:
	vim -p $(source) XSbench_header.hpp XSbench_shared_header.h

run:
	./$(program)
```
