```makefile
# Makefile for OpenMP offloading microXOR

CXX ?= clang++
CXXFLAGS ?= -std=c++17 -foffload=-march=sm_$(SM_VERSION) -fopenmp -Iinclude
LDFLAGS ?= -fopenmp

ifeq ($(DEBUG), yes)
	CXXFLAGS += -g -O0
else
	CXXFLAGS += -O3
endif

SRC = src
INC = include
OBJ = obj
EXE = microXOR.exe

CUFILES = $(SRC)/microXOR.cpp $(SRC)/main.cpp
DEPS = $(INC)/microXOR.hpp

OBJS = $(CUFILES:$(SRC)/%.cpp=$(OBJ)/%.o)


$(EXE): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $@ $(LDFLAGS)

$(OBJ)/%.o: $(SRC)/%.cpp $(DEPS) | obj
	$(CXX) $(CXXFLAGS) -c $< -o $@

obj:
	mkdir -p $(OBJ)

clean:
	rm -f $(OBJS) $(EXE)

.PHONY: clean
```
