# Makefile for CUDA microXOR using the Clang compiler

CXX_COMPILER ?= clang++
CUDA_ARCH ?= sm_80
SRC = src
INC = include
OBJ = obj
CXXFLAGS ?= -O3 -fopenmp -Xopenmp-target=nvptx64-nvidia-cuda -I$(INC) -std=c++17
LDFLAGS ?= -L/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/cuda/12.0/lib64 -L/global/common/software/nersc/pe/gpu/llvm/17.0.6/lib -lcudart_static -ldl -lrt -pthread

CUFILES = $(SRC)/microXOR.cpp $(SRC)/main.cpp
DEPS = $(INC)/microXOR.cuh
OBJS = $(CUFILES:$(SRC)/%.cpp=$(OBJ)/%.o)
EXE = microXOR.exe

$(EXE): $(OBJS)
	$(CXX_COMPILER) $(CXXFLAGS) $(OBJS) -o $(EXE) $(LDFLAGS)

$(OBJ)/%.o: $(SRC)/%.cpp $(DEPS) | obj
	$(CXX_COMPILER) $(CXXFLAGS) -c $< -o $@

obj:
	mkdir -p $(OBJ)

clean:
	rm -f $(OBJS) $(EXE)

.PHONY: clean