Here is the translated Makefile in one code block:

```
# Makefile for OpenMP-offload microXOR

SM_VERSION ?= 80
CXX_COMPILER ?= g++
OFFLOAD_CXX ?= offload
OFFLOAD_FLAGS ?= -fopenmp-targets=nvptx64-nvidia-cuda --cuda-device
ifneq ($(DEBUG), yes)
	CXXFLAGS += -O3
else
	CXXFLAGS += -g -G
endif

SRC = src
INC = include
OBJ = obj
CUFILES = $(SRC)/microXOR.cpp $(SRC)/main.cpp
DEPS = $(INC)/microXOR.hpp
OBJS = $(CUFILES:$(SRC)/%.cpp=$(OBJ)/%.o)
EXE = microXOR.exe

$(EXE): $(OBJS)
	$(CXX_COMPILER) -fopenmp $(OFFLOAD_FLAGS) $(OBJS) -o $(EXE)

$(OBJ)/%.o: $(SRC)/%.cpp $(DEPS) | obj
	$(CXX_COMPILER) -fopenmp $(OFFLOAD_FLAGS) $(CXXFLAGS) $< -o $@

obj:
	mkdir -p $(OBJ)

clean:
	rm -f $(OBJS) $(EXE)

.PHONY: clean

# Example usage:
# make SM_VERSION=80 CXX_COMPILER=clang++ CXX=g++
```

Note that I've assumed the user will use `g++` as the compiler and `nvptx64-nvidia-cuda` as the offload target. You can modify these to suit your needs.

Also note that you'll need to replace `.cu` files with `.cpp` files, since CUDA code is not compatible with OpenMP-offload. In this Makefile, I've replaced `microXOR.cu` and `main.cu` with `microXOR.cpp` and `main.cpp`, respectively.

Finally, make sure to install the necessary tools (e.g., `nvptx64-nvidia-cuda`) for offloading to work correctly.