```makefile
# Makefile for OpenMP-Offload microXOR

CXX ?= $(CXX_COMPILER)
CXXFLAGS ?= -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda -Xopenmp-target=nvptx64-nvidia-cuda -march=sm_$(SM_VERSION) -std=c++17
ifneq ($(DEBUG), yes)
	CXXFLAGS += -O3
else
	CXXFLAGS += -g
endif
LDFLAGS ?= -fopenmp

CPPFILES = src/microXOR.cpp src/main.cpp
DEPS = include/microXOR.hpp
OBJS = $(CPPFILES:src/%.cpp=obj/%.o)
EXE = microXOR.exe

$(EXE): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(EXE) $(LDFLAGS)

obj/%.o: src/%.cpp $(DEPS) | obj
	$(CXX) $(CXXFLAGS) -c $< -o $@

obj:
	mkdir -p obj

clean:
	rm -f $(OBJS) $(EXE)

.PHONY: clean
```