Here is the Makefile converted to compile as OpenMP-offload code:
```makefile
# Makefile for XSBench shared utilities

CXX = clang++
CUDA_CXX = nvcc
NVCC_ARCH = $(CUDA_ARCH)
COMPILE = COMPILER=$(COMPILER)

default: all

all: xsbench_shared.o

xsbench_shared.o: $(XSBECH_SHARED_HEADER_H) $(XSBECH_SHARED_SOURCE_FILE).c
    @echo "Compiling $<"
    $(CXX) -c -g3 -std=c++11 -O0 -Wall -Wno-deprecated-gpu-targets -fPIC -DUSE_OFFLOAD=$(CUDA_ARCH) \
        $(NVCC_CXXFLAGS) $(COMPILE) $(XSBECH_SHARED_SOURCE_FILE).c -o xsbench_shared.o

clean:
    rm -rf *.o
```
Note that I have assumed the following:

* The C++ compiler is `clang++` by default, but can be overridden with the `COMPILER` variable.
* The CUDA compiler is `nvcc` and the architecture is specified with the `CUDA_ARCH` variable.
* The header file is named `XSBECH_SHARED_HEADER_H` (note: I added a typo in the original filename) and the source file is named `$(XSBECH_SHARED_SOURCE_FILE).c`.
* The Makefile uses the `-fPIC` flag to compile position-independent code, which is required for OpenMP-offload.

To use this Makefile, you can run `make CUDA_ARCH=80 COMPILER=clang++` (or any other valid combination of flags) to build the shared utilities.