Here's how you can translate the Makefile to use the OpenMP-offload execution model.

```make
# User Options
COMPILER ?= clang
CUDA_ARCH ?= 80
OPTIMIZE ?= yes
DEBUG    ?= no
PROFILE  ?= no

# Program name & source code list
program = XSBench

source = \
Main.cu \
io.cu \
Simulation.cu \
GridInit.cu \
XSutils.cu \
Materials.cu

obj = $(source:.cu=.o)

# Sets Flags for OpenMP offload
CFLAGS := -fopenmp -D__CUDA_ARCH__=$(CUDA_ARCH) -std=c++14

# Sets Flags for compiler choice (clang or other)
ifeq ($(COMPILER),clang)
  CC = clang++
else ifeq ($(COMPILER),gcc)
  CC = g++
endif

# Debug Flags
ifeq ($(DEBUG),yes)
  CFLAGS += -g -G
endif

# Profiling Flags
ifeq ($(PROFILE),yes)
  CFLAGS += -pg
endif

# Optimization Flags
ifeq ($(OPTIMIZE),yes)
  CFLAGS += -O3
endif

# Target to Build
$(program): $(obj) XSbench_header.cuh Makefile
	$(CC) $(CFLAGS) $(obj) -o $@ -fopenacc

%.o: %.cu XSbench_header.cuh Makefile
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -rf $(program) $(obj)

edit:
	vim -p $(source) XSbench_header.cuh

run:
	./$(program)


io.cu:
#include "XSbench_header.cuh"

// ...

```

This Makefile includes the necessary flags to compile the code with OpenMP and offloading. The `CFLAGS` variable now includes `-fopenmp` for OpenMP support, `-D__CUDA_ARCH__=$(CUDA_ARCH)` to specify the CUDA architecture (assuming you're using a system with an NVIDIA GPU), and `-std=c++14` for C++14 compliance.

The compiler choice is set to clang or gcc depending on the `COMPILER` variable. If you want to use another compiler, you can modify this section accordingly.

Note that I've also included `-fopenacc` in the link step (`$(CC) $(CFLAGS) $(obj) -o $@ -fopenacc`) to enable offloading support for OpenACC-compliant compilers like clang.