Here is the translated Makefile:
```
# Makefile for OpenMP-offload microXOR

CXX ?= g++
SM_VERSION ?= 80
OFFLOAD_COMPILER ?= cl-clang++
OFFLOAD_FLAGS ?= -ccbin=nvcc --offload-architecture=${SM_VERSION}
ifneq ($(DEBUG), yes)
	CXXFLAGS += -O3
else
	CXXFLAGS += -g
endif

CXX_COMPILER ?= clang++

INC = include
SRC = src
OBJ = obj
DEPS = $(INC)/microXOR.hpp
CUFILES = $(SRC)/microXOR.cpp $(SRC)/main.cpp
OBJS = $(CUFILES:$(SRC)/%.cpp=$(OBJ)/%.o)
EXE = microXOR.exe

$(EXE): $(OBJS)
	$(CXX) $(CXXFLAGS) -fopenmp-targets=nvptx64-nvidia-cc${SM_VERSION} -I$(INC) $(OFFLOAD_FLAGS) $(OBJS) -o $(EXE)

$(OBJ)/%.o: $(SRC)/%.cpp $(DEPS) | obj
	$(CXX_COMPILER) $(CXXFLAGS) -fopenmp-targets=nvptx64-nvidia-cc${SM_VERSION} -I$(INC) -c $< -o $@

obj:
	mkdir -p $(OBJ)

clean:
	rm -f $(OBJS) $(EXE)
```
Note the following changes:

* The `NVCC` and `CUDA_ARCH` variables are no longer used. Instead, we use the `SM_VERSION` variable to specify the OpenMP-offload target architecture.
* We added the `-fopenmp-targets=nvptx64-nvidia-cc${SM_VERSION}` flag to enable OpenMP-offload compilation for NVIDIA GPUs with compute capability ${SM_VERSION}.
* The `CXX` compiler is now used instead of `NVCC`.
* We use the `cl-clang++` compiler as the offload compiler, which is a wrapper around the Clang compiler that generates PTX code.
* We added the `--offload-architecture=${SM_VERSION}` flag to specify the offload architecture for the compiler.

To build the code, you can run:
```
make SM_VERSION=80 CXX_COMPILER=clang++ OFFLOAD_COMPILER=cl-clang++
```