#!/bin/bash
#PBS -N translate_vllm
#PBS -l select=1:system=polaris
#PBS -l filesystems=home:eagle
#PBS -l walltime=1:00:00
#PBS -q debug
#PBS -A DemocAI

MODEL_NAME=Llama-3.3-70B-Instruct-Q4_K_L.gguf

# Activate vLLM environment
source /home/jhdavis/venvs/2024-04-29-vllm/bin/activate

# Set environment variables
export HTTP_PROXY="http://proxy.alcf.anl.gov:3128"
export HTTPS_PROXY="http://proxy.alcf.anl.gov:3128"
export LD_LIBRARY_PATH=$HOME/venvs/2024-04-29-vllm/lib64/python3.11/site-packages/nvidia/nvjitlink/lib:$LD_LIBRARY_PATH
export TMPDIR=/tmp/vllm && mkdir -p $TMPDIR
export VLLM_HOST_IP=127.0.0.1
export NO_PROXY=127.0.0.1,localhost
export CUDA_VISIBLE_DEVICES=0,1,2,3

# Copy model to /dev/shm/
echo -n "Copying model to /dev/shm/... "
cp $SCRATCH/$MODEL_NAME /dev/shm/
echo "Done"

# Start vLLM server
echo -n "Launching vLLM server process... "
vllm serve /dev/shm/$MODEL_NAME \
     --tokenizer meta-llama/Llama-3.3-70B-Instruct \
     --host 127.0.0.1 \
     --port 8000 \
     --api-key token_abc123 \
     --tensor-parallel-size 4 \
     --gpu-memory-utilization 0.95 \
     --enforce-eager \
     --enable-prefix-caching &
echo "Done"

VLLM_PID=$!  # Capture the PID of the server process

# Wait for server to start
echo "Waiting for vLLM server to become available... "
until curl -H "Authorization: Bearer token_abc123" -s http://127.0.0.1:8000/v1/models | grep -q "object"; do
    sleep 5
done
echo "Server confirmed available."

# Check memory utlization across devices
nvidia-smi

# Do translation
cd /home/jhdavis/llms4hpc/code-translation/src/translate/test
module use /soft/modulefiles
module load llvm cudatoolkit-standalone
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 25
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 26
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 27
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 28
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 29
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 30
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 31
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 32
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 33
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 34
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 35
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 36
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 37
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 38
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 39
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 40
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 41
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 42
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 43
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 44
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 45
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 46
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 47
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 48
bash translate.sh restate /dev/shm/$MODEL_NAME vllm microXOR 49

# Exit when finished
exit
