Here is the translated Makefile:
```makefile
# OpenMP-Offload makefile for compiling with NVIDIA GPU

# Set SM_VERSION to specify the target device (e.g., 80 for an NVIDIA GPU with compute capability 8.0)
SM_VERSION = 80

# Set CFLAGS to include necessary libraries and compiler flags
CFLAGS = -L/opt/nvidia/hpc_sdk/Linux_x86_64/23.9/math_libs/12.2/targets/x86_64-linux/lib/

# Set CXX to specify the compiler (e.g., clang)
CXX = clang

# Define OpenMP-Offload compilation flags
OFFLOAD_CFLAGS = -fopenmp-targets=nvptx64-nvidia-cuda=${SM_VERSION} \
                -Xopenmp-target=spir64-unknown-amd-gpu \
                -D__NVCC__

# Define CUDA library and include path
CUDA_LIB_PATH = /usr/lib/nvidia-cuda-toolkit/lib/
CUDA_INC_PATH = /usr/include/cuda/

# Define NVIDIA math library path (e.g., for cublas, cuBLAS, etc.)
NVIDIA_MATH_LIB_PATH = /opt/nvidia/hpc_sdk/Linux_x86_64/23.9/math_libs/12.2/targets/x86_64-linux/lib/

# C compiler
CC = gcc

# C++ compiler
CXX = clang++

# Object files
OBJS = main.o source_array.o init_device_sources.o cuda_memcpy.o build_exponential_table.o translate.o

# OpenMP-Offload compilation rules
%.o: %.c
    ${CXX} -c ${OFFLOAD_CFLAGS} ${CFLAGS} $<

%.o: %.cpp
    ${CXX} -c ${OFFLOAD_CFLAGS} ${CFLAGS} $<

main.o: main.c source_array.h init_device_sources.h cuda_memcpy.h build_exponential_table.h translate.h
source_array.o: source_array.c source_array.h init_device_sources.h cuda_memcpy.h build_exponential_table.h translate.h
init_device_sources.o: init_device_sources.cpp source_array.h init_device_sources.h cuda_memcpy.h build_exponential_table.h translate.h
cuda_memcpy.o: cuda_memcpy.cpp source_array.h init_device_sources.h cuda_memcpy.h build_exponential_table.h translate.h
build_exponential_table.o: build_exponential_table.c source_array.h init_device_sources.h cuda_memcpy.h build_exponential_table.h translate.h
translate.o: translate.cpp source_array.h init_device_sources.h cuda_memcpy.h build_exponential_table.h translate.h

# Linking rule
%.o: %.cpp $(OBJS)
    ${CXX} -o $@ ${OFFLOAD_CFLAGS} ${CFLAGS} $< $(OBJS)

%.o: %.c $(OBJS)
    ${CC} -o $@ ${OFFLOAD_CFLAGS} ${CFLAGS} $< $(OBJS)

# Default target
default: main

main: main.o source_array.o init_device_sources.o cuda_memcpy.o build_exponential_table.o translate.o
    ${CXX} -o main ${OFFLOAD_CFLAGS} ${CFLAGS} main.o $(OBJS) \
      -lcudart -lnvidia-ml -L${CUDA_LIB_PATH} -l${SM_VERSION}-cublas-cuda -lm

.PHONY: clean
clean:
    rm -f *.o main
```
Note that this makefile assumes you have the necessary NVIDIA libraries and compiler flags installed. Also, the compilation rules assume that each source file has corresponding header files in the same directory.

To build the code using this makefile, use the following command (assuming the current working directory is `include/`):
```bash
cd include/
make SM_VERSION=80 CFLAGS=-L/opt/nvidia/hpc_sdk/Linux_x86_64/23.9/math_libs/12.2/targets/x86_64-linux/lib/ CXX=clang
```
This will compile the code using the NVIDIA GPU with compute capability 8.0 and link against the necessary libraries.

Please note that this is just a basic example, and you may need to modify the makefile depending on your specific use case.