Here is the translated Makefile:
```makefile
# Makefile for OpenMP microXOR

CXX ?= clang++
SM_VERSION ?= 80
CXXFLAGS ?= -fopenmp -std=c++17 -march=nvptx64-nvidia-cuda=${SM_VERSION}
ifeq ($(DEBUG), yes)
	CXXFLAGS += -g -G
else
	CXXFLAGS += -O3
endif
LDFLAGS ?= -lcudart

CPPFILES = src/microXOR.cpp src/main.cpp
HDRS = include/microXOR.hpp

OBJS = $(CPPFILES:src/%.cpp=obj/%.o)

EXE = microXOR.exe

$(EXE): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $(OBJS) $(LDFLAGS)

obj/%.o: src/%.cpp $(HDRS) | obj
	$(CXX) $(CXXFLAGS) -c $< -o $@

obj:
	mkdir -p $(OBJ)

clean:
	rm -f $(OBJS) $(EXE)

.PHONY: clean

# Define the offload directive
%.offload.cpp: %.cpp
	sed -e 's/^/openmp target nvptx64-nvidia-cuda=${SM_VERSION}:\n/' $< > $@
```
Note that I assumed you want to use clang++ as the CXX_COMPILER, and that you will compile this code using `make SM_VERSION=80 CXX_COMPILER=clang++` to build the code for a system with an NVIDIA GPU with compute capability 80 compiled with clang++. Also note that I used `.cpp` and `.hpp` filenames instead of `.cu` and `.cuh`, as per your request.