```makefile
# Makefile for OpenMP offloading microXOR

CXX ?= clang++
CXXFLAGS ?= -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda -std=c++17
LDFLAGS ?= -lcudart

ifeq ($(SM_VERSION), )
  $(error SM_VERSION must be set, e.g., make SM_VERSION=80)
endif

ifeq ($(CXX_COMPILER), )
  $(error CXX_COMPILER must be set, e.g., make CXX_COMPILER=g++)
endif

CXXFLAGS += -mcpu=sm_$(SM_VERSION)

SRC = src
INC = include
OBJ = obj
EXE = microXOR.exe

CPPFILES = $(SRC)/microXOR.cpp $(SRC)/main.cpp
DEPS = $(INC)/microXOR.hpp
OBJS = $(CPPFILES:$(SRC)/%.cpp=$(OBJ)/%.o)


$(EXE): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(EXE) $(LDFLAGS)

$(OBJ)/%.o: $(SRC)/%.cpp $(DEPS) | obj
	$(CXX) $(CXXFLAGS) -c $< -o $@

obj:
	mkdir -p $(OBJ)

clean:
	rm -f $(OBJS) $(EXE)

.PHONY: clean
```
