Here is the translated Makefile:
```makefile
# Define variables
SM_VERSION = $(shell echo "80")
CFLAGS = -L/opt/nvidia/hpc_sdk/Linux_x86_64/23.9/math_libs/12.2/targets/x86_64-linux/lib/
CUDA_CXXFlags = -gencode arch=sm_$(SM_VERSION) $CFLAGS
CUDA_CFlags = $(CUDA_CXXFlags)
LIBS = $CFLAGS

# Include directories and libraries for OpenMP offload
#include_dirs = -I/opt/nvidia/hpc_sdk/Linux_x86_64/23.9/cuda/include/
lib_dirs = -L/opt/nvidia/hpc_sdk/Linux_x86_64/23.9/math_libs/12.2/targets/x86_64-linux/lib/

# Compile and link the code
cc = gcc
ompflags = -fopenmp

all: main.o table.o sources_h.o sources_d.o buildExponentialTable.c

main.o: main.c
	$(cc) $(CUDA_CXXFlags) $(ompflags) -c main.c

table.o: table.c
	$(cc) $(CUDA_CXXFlags) $(ompflags) -c table.c

sources_h.o: sources_h.c
	$(cc) $(CUDA_CXXFlags) $(ompflags) -c sources_h.c

sources_d.o: sources_d.c
	$(cc) $(CUDA_CXXFlags) $(ompflags) -c sources_d.c

buildExponentialTable.o: buildExponentialTable.c
	$(cc) $(CUDA_CXXFlags) $(ompflags) -c buildExponentialTable.c

buildExponentialTable: table.h main.h source.h Table.c
	$(cc) $(CUDA_CXXFlags) $(omflags) -fopenmp -c table.c -o table.o \
	$(cc) $(CUDA_CXXFlags) $(omflags) -fopenmp -c sources_h.c -o sources_h.o \
	$(cc) $(CUDA_CXXFlags) $(omflags) -fopenmp -c sources_d.c -o sources_d.o \
	$(cc) $(CUDA_CXXFlags) $(omflags) -fopenmp buildExponentialTable.c -o buildExponentialTable

sources: sources_h.o sources_d.o
	$(cc) $(LIBS) $(cuda_cxx_flags) -c sources.h.o -o sources_h.o \
	$(cc) $(LIBS) $(cuda_cxx_flags) -c sources.d.o -o sources_d.o

# Link the source files together with the device code
all: main.o table.o sources_h.o sources_d.o buildExponentialTable

main: main.o table.o sources_h.o sources_d.o
	$(cc) $(LIBS) $(cuda_cxx_flags) -fopenmp -o main main.o table.o sources_h.o sources_d.o

table: table.o
	$(cc) $(LIBS) $(cuda_cxx_flags) -fopenmp -o table table.o

sources_h: sources_h.o
	$(cc) $(LIBS) $(cuda_cxx_flags) -fopenmp -o sources_h sources_h.o

sources_d: sources_d.o
	$(cc) $(LIBS) $(cuda_cxx_flags) -fopenmp -o sources_d sources_d.o

buildExponentialTable: buildExponentialTable.o table.h main.h source.h Table.c
	$(cc) $(LIBS) $(cuda_cxx_flags) -fopenmp -c table.h main.h source.h -o table.o \
	$(cc) $(LIBS) $(cuda_cxx_flags) -fopenmp sources_h.c -o sources_h.o \
	$(cc) $(LIBS) $(cuda_cxx_flags) -fopenmp sources_d.c -o sources_d.o \
	$(cc) $(LIBS) $(cuda_cxx_flags) buildExponentialTable.c -o buildExponentialTable
```
Note that I assumed the file names for the source files (`main.c`, `table.c`, etc.) are as you mentioned. Also, I used the `gcc` compiler and the OpenMP flags `-fopenmp` to enable offloading.

Please note that this Makefile is just a suggestion, and you may need to adjust it according to your specific requirements and environment.