Here is the Makefile translated to use OpenMP-offload:
```c
# User Options
CUDA_ARCH ?= 80
COMPILER    ?= llvm
OPTIMIZE    ?= yes
DEBUG       ?= no
PROFILE     ?= no

# Program name & source code list
program = XSBench

source = \
Main.cu \
io.cu \
Simulation.cu \
GridInit.cu \
XSutils.cu \
Materials.cu

obj = $(source:.cu=.o)

# Sets Flags
CFLAGS := -O3
LDFLAGS =

# Compiler flags for clang/llvm compiler with OpenMP-offload support
ifeq ($(COMPILER),llvm)
  CC = clang++
  CFLAGS += -fopenmp -foffload
endif

# Debug Flags
ifeq ($(DEBUG),yes)
  CFLAGS += -g -G
endif

# Profiling Flags
ifeq ($(PROFILE),yes)
  CFLAGS += -pg
endif

# Optimization Flags
ifeq ($(OPTIMIZE),yes)
  CFLAGS += -O3
endif

# Compiler flags for NVIDIA compiler with CUDA support (optional)
ifeq ($(COMPILER),nvcc)
  CC = nvcc
  CFLAGS += -arch=sm_$(CUDA_ARCH) -std=c++14
endif

# Targets to Build
$(program): $(obj) XSbench_header.cuh Makefile
	$(CC) $(CFLAGS) $(obj) -o $@ $(LDFLAGS)

%.o: %.cu XSbench_header.cuh Makefile
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -rf $(program) $(obj)

edit:
	vim -p $(source) XSbench_header.cuh

run:
	./$(program)
```
Note that I've added the `-fopenmp` flag to enable OpenMP support, and the `-foffload` flag to enable offloading. I've also removed the CUDA-specific flags, as they are no longer needed with OpenMP-offload. Additionally, I've changed the compiler to `clang++`, which is a common choice for compiling C++ code with OpenMP support.