Here's the translated Makefile:

```
# User Options
COMPILER ?= clang
OPTIMIZE ?= yes
DEBUG ?= no
PROFILE ?= no
CUDA_ARCH ?=

# Program name & source code list
program = XSBench

source = \
Main.cu \
io.cu \
Simulation.cu \
GridInit.cu \
XSutils.cu \
Materials.cu

obj = $(source:.cu=.o)

# Sets Flags
CFLAGS := 
LDFLAGS = -lm

# LLVM Compiler
ifeq ($(COMPILER),clang)
  CC = clang++-offload
  CXX = clang++
  CFLAGS += -Xcudarc --cuda-generate-code-for-all-gpus
endif

# Debug Flags
ifeq ($(DEBUG),yes)
  CFLAGS += -g -G
  LDFLAGS  += -g -G
endif

# Profiling Flags
ifeq ($(PROFILE),yes)
  CFLAGS += -pg
  LDFLAGS  += -pg
endif

# Optimization Flags
ifeq ($(OPTIMIZE),yes)
  CFLAGS += -O3
endif

# CUDA Architecture
ifneq ($(CUDA_ARCH),)
  CFLAGS += --cuda-gencode=$(CUDA_ARCH)
endif

# Targets to Build
$(program): $(obj) XSbench_header.cuh Makefile
	$(CC) $(CFLAGS) $(obj) -o $@ $(LDFLAGS)

%.o: %.cu XSbench_header.cuh Makefile
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -rf $(program) $(obj)

edit:
	vim -p $(source) XSbench_header.cuh

run:
	./$(program)
```

Please note that the `clang` compiler is used here. If you want to use a different compiler, just change the value of `COMPILER` variable.

Also note that `-Xcudarc --cuda-generate-code-for-all-gpus` flag is used to allow offloading code to all devices in the system, but it's not necessary if you have only one device. You can remove this flag if you don't need it.

Remember to use `make CUDA_ARCH=80 COMPILER=llvm` command to compile your code with clang compiler for a system with an NVIDIA GPU with compute capability 80.