Here is the translated Makefile:

```makefile
#===============================================================================
# User Options
#===============================================================================

OMP_OFFLOAD    ?= yes
SM_VERSION  ?= 80
CFLAGS       += -I/opt/nvidia/hpc_sdk/Linux_x86_64/23.9/math_libs/12.2/targets/x86_64-linux/lib/
CXX          = clang
NVCC         = nvcc

#===============================================================================
# Program name & source code list
#===============================================================================

program = SimpleMOC-kernel

source = \
main.c \
kernel.c \
init.c \
io.c

obj = $(source:.c=.o)

#===============================================================================
# Sets Flags
#===============================================================================

# Standard Flags
override CFLAGS += -march=sm_$(SM_VERSION) -I/usr/local/cuda/include -fopenmp-targets=nvptx64-nvidia-cuda

# Offload Flags
ifeq ($(OMP_OFFLOAD),yes)
  override CXXFLAGS += -fopenmp-targets=nvptx64-nvidia-cuda -fopenmp-offload
endif

# Linker Flags
LDFLAGS = -lm -lcurand

#===============================================================================
# Targets to Build
#===============================================================================

$(program): $(obj) SimpleMOC-kernel_header.h
	$(NVCC) $(CFLAGS) $(CXXFLAGS) $(obj) -o $@ $(LDFLAGS)

%.o: %.c
	$(CXX) $(CFLAGS) -fopenmp-targets=nvptx64-nvidia-cuda -c $< -o $@

clean:
	rm -rf $(program) $(obj)

edit:
	vim -p $(source) SimpleMOC-kernel_header.h

run:
	./$(program)


#===============================================================================
# Offload Options
#===============================================================================

NVCC_OPTIONS = --gpu-architecture=sm_$(SM_VERSION) --use_fast_math
ifneq ($(OMP_OFFLOAD),yes)
  NVCC_OPTIONS += -DNO_OFFLOAD
endif
```

Note that I've assumed the user will compile this code using a compiler like clang and NVIDIA libraries at /opt/nvidia/hpc_sdk/Linux_x86_64/23.9/math_libs/12.2/targets/x86_64-linux/lib/. The CXX variable is used to specify the compiler, which in this case is clang.