Here is the translated Makefile:

```
# User Options
COMPILER    ?= clang-ompoffload
OPTIMIZE    ?= yes
DEBUG       ?= no
PROFILE     ?= no
CUDA_ARCH   ?= 80

# Program name & source code list
program = XSBench

source = \
Main.cu \
io.cu \
Simulation.cu \
GridInit.cu \
XSutils.cu \
Materials.cu

obj = $(source:.cu=.o)

# Sets Flags
CFLAGS := 
LDFLAGS = -lm

# LLVM Compiler with OpenMP and Offload Support
ifeq ($(COMPILER),clang-ompoffload)
  CC = clang++ -fopenmp-targets=nvptx64-nvidia-cuda=11.1
endif

# Debug Flags
ifeq ($(DEBUG),yes)
  CFLAGS += -g -G
  LDFLAGS  += -g -G
endif

# Profiling Flags
ifeq ($(PROFILE),yes)
  CFLAGS += -pg
  LDFLAGS  += -pg
endif

# Optimization Flags
ifeq ($(OPTIMIZE),yes)
  CFLAGS += -O3
endif

# Offload Options (default: all available NVIDIA devices)
CFLAGS += -fopenmp-targets=nvptx64-nvidia-cuda=11.1 \
          -foffload=cuda,targets=nvptx64-nvidia-cuda=11.1 \
          --cuda-gpu-arch=$(CUDA_ARCH)

# Targets to Build
$(program): $(obj) XSbench_header.h Makefile
	$(CC) $(CFLAGS) $(obj) -o $@ $(LDFLAGS)

%.o: %.cu XSbench_header.h Makefile
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -rf $(program) $(obj)

edit:
	vim -p $(source) XSbench_header.h

run:
	./$(program)
```

Note that I have modified the Makefile to use clang++ instead of nvcc, and added flags for OpenMP and offload support. The `CUDA_ARCH` variable is used to specify the target architecture (in this case, NVIDIA GPU with compute capability 80). Also note that you may need to adjust the compiler version in the flag `-fopenmp-targets=nvptx64-nvidia-cuda=11.1` depending on your specific system and CUDA version.