Here is the translated Makefile:

```make
CUDA_ARCH ?= 80
COMPILER ?= llvm

CC = ${COMPILER} -fopenmp
CXX = ${CC}
LD = ${CC}

CFLAGS = -Wall -Wextra -O3 -arch=$(CUDA_ARCH)
LDFLAGS = -lm
OPENMP_CFLAGS = -fopenmp-targets=nvptx64-nvvm34.9

program = XSBench

source = \
Main.cu \
io.cu \
Simulation.cu \
GridInit.cu \
XSutils.cu \
Materials.cu

obj = $(source:.cu=.o)

$(program): $(obj) XSbench_header.h Makefile
	$(CC) $(CFLAGS) $(OPENMP_CFLAGS) $(obj) -o $@ $(LDFLAGS)

%.o: %.c XSbench_header.h Makefile
	$(CC) $(CFLAGS) $(OPENMP_CFLAGS) -c $< -o $@

clean:
	rm -rf $(program) $(obj)

edit:
	vim -p $(source) XSbench_header.h

run:
	./$(program)
```

This makefile assumes that the user will compile the code using `make CUDA_ARCH=80 COMPILER=llvm` to build the code for a system with an NVIDIA GPU with compute capability 80 and compiler with the clang compiler. It also sets the flags necessary for OpenMP compilation, including the `-fopenmp-targets=nvptx64-nvvm34.9` flag, which tells the compiler to target the nvptx64 architecture with NVVM version 3.4.9.